# This script requires the following secrets to be set in the repository settings:
# - SELF_PASSWORD
#

name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ===== SETUPS ======

      - name: Setup codebase
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Increment version
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          wget -O tmp-increment_version.sh https://raw.githubusercontent.com/L1ghtDream/report/cdn/increment_version.sh
          chmod +x tmp-increment_version.sh
          ./tmp-increment_version.sh


      # ===== BUILD ======


      - name: Execute Gradle build
        run: gradle build


      # ===== EXTERNAL SCRIPTS =====

      - name: External scripts
        run: |
          wget -O tmp-environment_variables.sh https://raw.githubusercontent.com/L1ghtDream/report/cdn/environment_variables.sh
          chmod +x tmp-environment_variables.sh
          ./tmp-environment_variables.sh ${{ github.REPOSITORY }}
          
          wget -O tmp-create_readme_template.sh https://raw.githubusercontent.com/L1ghtDream/report/cdn/create_readme_template.sh
          chmod +x tmp-create_readme_template.sh
          ./tmp-create_readme_template.sh


      # ===== PUBLISH ======


      - name: Uploading artifacts
        run: |
          wget -O tmp-publish.sh https://raw.githubusercontent.com/L1ghtDream/report/cdn/publish.sh 
          chmod +x tmp-publish.sh 
          ./tmp-publish.sh ${{ github.REPOSITORY }} ${{ secrets.GITHUB_TOKEN }} ${{ secrets.SELF_PASSWORD }}

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.VERSION }}"
          prerelease: false
          title: "${{ env.VERSION }}"
          files: |
            build/libs/*.jar


      # ===== RENDERS ======


      - name: "README.md Render"
        uses: varunsridharan/action-dynamic-readme@1.2
        with:
          committer_name: "Radu Voinea"
          committer_email: "contact@voienaradu.com"
          commit_message: "Updated README.md versions"
          files: |
            tmp/README-template.md=README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
          ARTIFACT: ${{ env.ARTIFACT }}
          GROUP: ${{ env.GROUP }}
          GITHUB_USERNAME: ${{ github.REPOSITORY_OWNER }}
          REPOSITORY: ${{ github.REPOSITORY }}
          REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}